artifact_location: file:c:/Users/Administrator/Desktop/digitization-pid/notebooks/model/runs/mlflow/220740345223810999
creation_time: 1760783702082
experiment_id: '220740345223810999'
last_update_time: 1760783702082
lifecycle_stage: active
name: runs
