artifact_location: file:c:/Users/Administrator/Desktop/digitization-pid/notebooks/model/runs/mlflow/0
creation_time: 1760783702063
experiment_id: '0'
last_update_time: 1760783702063
lifecycle_stage: active
name: Default
